apiVersion: v1
kind: Secret
metadata:
  name: smart-retail-x-secrets
  namespace: smart-retail-x
type: Opaque
stringData:
  POSTGRES_PASSWORD: "change-me-postgres-password"
  DATABASE_URL: "postgresql://smartretailx:change-me-postgres-password@postgres:5432/smartretailx"
  RABBITMQ_DEFAULT_PASS: "change-me-rabbitmq-password"
  RABBITMQ_URI: "amqp://smartretailx:change-me-rabbitmq-password@rabbitmq:5672"
  BETTER_AUTH_SECRET: "change-me-to-a-production-secret-minimum-32-chars"
  OPENAI_API_KEY: ""
  ASSEMBLYAI_API_KEY: ""
  HF_TOKEN: ""
  SINLAMA_API_KEY: ""
  WHISPER_API_URL: ""
