/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicAuthRouteImport } from './routes/_public/$auth'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/_user'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedUserOrdersRouteImport } from './routes/_authenticated/_user/orders'
import { Route as AuthenticatedUserCartRouteImport } from './routes/_authenticated/_user/cart'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedAdminAdminStockRouteImport } from './routes/_authenticated/_admin/admin.stock'
import { Route as AuthenticatedAdminAdminProductsRouteImport } from './routes/_authenticated/_admin/admin.products'
import { Route as AuthenticatedAdminAdminOrdersRouteImport } from './routes/_authenticated/_admin/admin.orders'
import { Route as AuthenticatedAdminAdminCategoriesRouteImport } from './routes/_authenticated/_admin/admin.categories'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public/$auth',
  path: '/$auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserOrdersRoute = AuthenticatedUserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedUserCartRoute = AuthenticatedUserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminStockRoute =
  AuthenticatedAdminAdminStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminProductsRoute =
  AuthenticatedAdminAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrdersRoute =
  AuthenticatedAdminAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCategoriesRoute =
  AuthenticatedAdminAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$auth': typeof PublicAuthRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/cart': typeof AuthenticatedUserCartRoute
  '/orders': typeof AuthenticatedUserOrdersRoute
  '/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$auth': typeof PublicAuthRoute
  '/cart': typeof AuthenticatedUserCartRoute
  '/orders': typeof AuthenticatedUserOrdersRoute
  '/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_user': typeof AuthenticatedUserRouteWithChildren
  '/_public/$auth': typeof PublicAuthRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/_user/cart': typeof AuthenticatedUserCartRoute
  '/_authenticated/_user/orders': typeof AuthenticatedUserOrdersRoute
  '/_authenticated/_admin/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/_authenticated/_admin/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/_authenticated/_admin/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/_authenticated/_admin/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$auth'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$auth'
    | '/cart'
    | '/orders'
    | '/admin/categories'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stock'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/_user'
    | '/_public/$auth'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_user/cart'
    | '/_authenticated/_user/orders'
    | '/_authenticated/_admin/admin/categories'
    | '/_authenticated/_admin/admin/orders'
    | '/_authenticated/_admin/admin/products'
    | '/_authenticated/_admin/admin/stock'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicAuthRoute: typeof PublicAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/$auth': {
      id: '/_public/$auth'
      path: '/$auth'
      fullPath: '/$auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_user/orders': {
      id: '/_authenticated/_user/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedUserOrdersRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/cart': {
      id: '/_authenticated/_user/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedUserCartRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/stock': {
      id: '/_authenticated/_admin/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/products': {
      id: '/_authenticated/_admin/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/orders': {
      id: '/_authenticated/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/categories': {
      id: '/_authenticated/_admin/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminCategoriesRoute: typeof AuthenticatedAdminAdminCategoriesRoute
  AuthenticatedAdminAdminOrdersRoute: typeof AuthenticatedAdminAdminOrdersRoute
  AuthenticatedAdminAdminProductsRoute: typeof AuthenticatedAdminAdminProductsRoute
  AuthenticatedAdminAdminStockRoute: typeof AuthenticatedAdminAdminStockRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminCategoriesRoute:
      AuthenticatedAdminAdminCategoriesRoute,
    AuthenticatedAdminAdminOrdersRoute: AuthenticatedAdminAdminOrdersRoute,
    AuthenticatedAdminAdminProductsRoute: AuthenticatedAdminAdminProductsRoute,
    AuthenticatedAdminAdminStockRoute: AuthenticatedAdminAdminStockRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserCartRoute: typeof AuthenticatedUserCartRoute
  AuthenticatedUserOrdersRoute: typeof AuthenticatedUserOrdersRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserCartRoute: AuthenticatedUserCartRoute,
  AuthenticatedUserOrdersRoute: AuthenticatedUserOrdersRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicAuthRoute: PublicAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
