/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicAuthRouteImport } from './routes/_public/$auth'
import { Route as AuthenticatedUserRouteImport } from './routes/_authenticated/_user'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedUserVoiceAssistantRouteImport } from './routes/_authenticated/_user/voice-assistant'
import { Route as AuthenticatedUserUserLoyaltyRouteImport } from './routes/_authenticated/_user/user-loyalty'
import { Route as AuthenticatedUserOrdersRouteImport } from './routes/_authenticated/_user/orders'
import { Route as AuthenticatedUserCartRouteImport } from './routes/_authenticated/_user/cart'
import { Route as AuthenticatedAdminAdminRouteImport } from './routes/_authenticated/_admin/admin'
import { Route as AuthenticatedAdminAdminIndexRouteImport } from './routes/_authenticated/_admin/admin.index'
import { Route as AuthenticatedUserProductsProductIdRouteImport } from './routes/_authenticated/_user/products.$productId'
import { Route as AuthenticatedAdminAdminTiersRouteImport } from './routes/_authenticated/_admin/admin.tiers'
import { Route as AuthenticatedAdminAdminTierDetailsRouteImport } from './routes/_authenticated/_admin/admin.tier-details'
import { Route as AuthenticatedAdminAdminStockRouteImport } from './routes/_authenticated/_admin/admin.stock'
import { Route as AuthenticatedAdminAdminProductsRouteImport } from './routes/_authenticated/_admin/admin.products'
import { Route as AuthenticatedAdminAdminOrdersRouteImport } from './routes/_authenticated/_admin/admin.orders'
import { Route as AuthenticatedAdminAdminLoyaltyRouteImport } from './routes/_authenticated/_admin/admin.loyalty'
import { Route as AuthenticatedAdminAdminCustomersRouteImport } from './routes/_authenticated/_admin/admin.customers'
import { Route as AuthenticatedAdminAdminCategoriesRouteImport } from './routes/_authenticated/_admin/admin.categories'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/_public/$auth',
  path: '/$auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUserRoute = AuthenticatedUserRouteImport.update({
  id: '/_user',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserVoiceAssistantRoute =
  AuthenticatedUserVoiceAssistantRouteImport.update({
    id: '/voice-assistant',
    path: '/voice-assistant',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserUserLoyaltyRoute =
  AuthenticatedUserUserLoyaltyRouteImport.update({
    id: '/user-loyalty',
    path: '/user-loyalty',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedUserOrdersRoute = AuthenticatedUserOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedUserCartRoute = AuthenticatedUserCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AuthenticatedUserRoute,
} as any)
const AuthenticatedAdminAdminRoute = AuthenticatedAdminAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAdminIndexRoute =
  AuthenticatedAdminAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedUserProductsProductIdRoute =
  AuthenticatedUserProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AuthenticatedUserRoute,
  } as any)
const AuthenticatedAdminAdminTiersRoute =
  AuthenticatedAdminAdminTiersRouteImport.update({
    id: '/tiers',
    path: '/tiers',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminTierDetailsRoute =
  AuthenticatedAdminAdminTierDetailsRouteImport.update({
    id: '/tier-details',
    path: '/tier-details',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminStockRoute =
  AuthenticatedAdminAdminStockRouteImport.update({
    id: '/stock',
    path: '/stock',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminProductsRoute =
  AuthenticatedAdminAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminOrdersRoute =
  AuthenticatedAdminAdminOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminLoyaltyRoute =
  AuthenticatedAdminAdminLoyaltyRouteImport.update({
    id: '/loyalty',
    path: '/loyalty',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCustomersRoute =
  AuthenticatedAdminAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)
const AuthenticatedAdminAdminCategoriesRoute =
  AuthenticatedAdminAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AuthenticatedAdminAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$auth': typeof PublicAuthRoute
  '/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/cart': typeof AuthenticatedUserCartRoute
  '/orders': typeof AuthenticatedUserOrdersRoute
  '/user-loyalty': typeof AuthenticatedUserUserLoyaltyRoute
  '/voice-assistant': typeof AuthenticatedUserVoiceAssistantRoute
  '/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/admin/customers': typeof AuthenticatedAdminAdminCustomersRoute
  '/admin/loyalty': typeof AuthenticatedAdminAdminLoyaltyRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/admin/tier-details': typeof AuthenticatedAdminAdminTierDetailsRoute
  '/admin/tiers': typeof AuthenticatedAdminAdminTiersRoute
  '/products/$productId': typeof AuthenticatedUserProductsProductIdRoute
  '/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$auth': typeof PublicAuthRoute
  '/cart': typeof AuthenticatedUserCartRoute
  '/orders': typeof AuthenticatedUserOrdersRoute
  '/user-loyalty': typeof AuthenticatedUserUserLoyaltyRoute
  '/voice-assistant': typeof AuthenticatedUserVoiceAssistantRoute
  '/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/admin/customers': typeof AuthenticatedAdminAdminCustomersRoute
  '/admin/loyalty': typeof AuthenticatedAdminAdminLoyaltyRoute
  '/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/admin/tier-details': typeof AuthenticatedAdminAdminTierDetailsRoute
  '/admin/tiers': typeof AuthenticatedAdminAdminTiersRoute
  '/products/$productId': typeof AuthenticatedUserProductsProductIdRoute
  '/admin': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_user': typeof AuthenticatedUserRouteWithChildren
  '/_public/$auth': typeof PublicAuthRoute
  '/_authenticated/_admin/admin': typeof AuthenticatedAdminAdminRouteWithChildren
  '/_authenticated/_user/cart': typeof AuthenticatedUserCartRoute
  '/_authenticated/_user/orders': typeof AuthenticatedUserOrdersRoute
  '/_authenticated/_user/user-loyalty': typeof AuthenticatedUserUserLoyaltyRoute
  '/_authenticated/_user/voice-assistant': typeof AuthenticatedUserVoiceAssistantRoute
  '/_authenticated/_admin/admin/categories': typeof AuthenticatedAdminAdminCategoriesRoute
  '/_authenticated/_admin/admin/customers': typeof AuthenticatedAdminAdminCustomersRoute
  '/_authenticated/_admin/admin/loyalty': typeof AuthenticatedAdminAdminLoyaltyRoute
  '/_authenticated/_admin/admin/orders': typeof AuthenticatedAdminAdminOrdersRoute
  '/_authenticated/_admin/admin/products': typeof AuthenticatedAdminAdminProductsRoute
  '/_authenticated/_admin/admin/stock': typeof AuthenticatedAdminAdminStockRoute
  '/_authenticated/_admin/admin/tier-details': typeof AuthenticatedAdminAdminTierDetailsRoute
  '/_authenticated/_admin/admin/tiers': typeof AuthenticatedAdminAdminTiersRoute
  '/_authenticated/_user/products/$productId': typeof AuthenticatedUserProductsProductIdRoute
  '/_authenticated/_admin/admin/': typeof AuthenticatedAdminAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$auth'
    | '/admin'
    | '/cart'
    | '/orders'
    | '/user-loyalty'
    | '/voice-assistant'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/tier-details'
    | '/admin/tiers'
    | '/products/$productId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$auth'
    | '/cart'
    | '/orders'
    | '/user-loyalty'
    | '/voice-assistant'
    | '/admin/categories'
    | '/admin/customers'
    | '/admin/loyalty'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/stock'
    | '/admin/tier-details'
    | '/admin/tiers'
    | '/products/$productId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_admin'
    | '/_authenticated/_user'
    | '/_public/$auth'
    | '/_authenticated/_admin/admin'
    | '/_authenticated/_user/cart'
    | '/_authenticated/_user/orders'
    | '/_authenticated/_user/user-loyalty'
    | '/_authenticated/_user/voice-assistant'
    | '/_authenticated/_admin/admin/categories'
    | '/_authenticated/_admin/admin/customers'
    | '/_authenticated/_admin/admin/loyalty'
    | '/_authenticated/_admin/admin/orders'
    | '/_authenticated/_admin/admin/products'
    | '/_authenticated/_admin/admin/stock'
    | '/_authenticated/_admin/admin/tier-details'
    | '/_authenticated/_admin/admin/tiers'
    | '/_authenticated/_user/products/$productId'
    | '/_authenticated/_admin/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicAuthRoute: typeof PublicAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/$auth': {
      id: '/_public/$auth'
      path: '/$auth'
      fullPath: '/$auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_user': {
      id: '/_authenticated/_user'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedUserRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_user/voice-assistant': {
      id: '/_authenticated/_user/voice-assistant'
      path: '/voice-assistant'
      fullPath: '/voice-assistant'
      preLoaderRoute: typeof AuthenticatedUserVoiceAssistantRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/user-loyalty': {
      id: '/_authenticated/_user/user-loyalty'
      path: '/user-loyalty'
      fullPath: '/user-loyalty'
      preLoaderRoute: typeof AuthenticatedUserUserLoyaltyRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/orders': {
      id: '/_authenticated/_user/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedUserOrdersRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_user/cart': {
      id: '/_authenticated/_user/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AuthenticatedUserCartRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_admin/admin': {
      id: '/_authenticated/_admin/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminAdminRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/admin/': {
      id: '/_authenticated/_admin/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_user/products/$productId': {
      id: '/_authenticated/_user/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof AuthenticatedUserProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedUserRoute
    }
    '/_authenticated/_admin/admin/tiers': {
      id: '/_authenticated/_admin/admin/tiers'
      path: '/tiers'
      fullPath: '/admin/tiers'
      preLoaderRoute: typeof AuthenticatedAdminAdminTiersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/tier-details': {
      id: '/_authenticated/_admin/admin/tier-details'
      path: '/tier-details'
      fullPath: '/admin/tier-details'
      preLoaderRoute: typeof AuthenticatedAdminAdminTierDetailsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/stock': {
      id: '/_authenticated/_admin/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/products': {
      id: '/_authenticated/_admin/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/orders': {
      id: '/_authenticated/_admin/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AuthenticatedAdminAdminOrdersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/loyalty': {
      id: '/_authenticated/_admin/admin/loyalty'
      path: '/loyalty'
      fullPath: '/admin/loyalty'
      preLoaderRoute: typeof AuthenticatedAdminAdminLoyaltyRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/customers': {
      id: '/_authenticated/_admin/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
    '/_authenticated/_admin/admin/categories': {
      id: '/_authenticated/_admin/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AuthenticatedAdminAdminCategoriesRouteImport
      parentRoute: typeof AuthenticatedAdminAdminRoute
    }
  }
}

interface AuthenticatedAdminAdminRouteChildren {
  AuthenticatedAdminAdminCategoriesRoute: typeof AuthenticatedAdminAdminCategoriesRoute
  AuthenticatedAdminAdminCustomersRoute: typeof AuthenticatedAdminAdminCustomersRoute
  AuthenticatedAdminAdminLoyaltyRoute: typeof AuthenticatedAdminAdminLoyaltyRoute
  AuthenticatedAdminAdminOrdersRoute: typeof AuthenticatedAdminAdminOrdersRoute
  AuthenticatedAdminAdminProductsRoute: typeof AuthenticatedAdminAdminProductsRoute
  AuthenticatedAdminAdminStockRoute: typeof AuthenticatedAdminAdminStockRoute
  AuthenticatedAdminAdminTierDetailsRoute: typeof AuthenticatedAdminAdminTierDetailsRoute
  AuthenticatedAdminAdminTiersRoute: typeof AuthenticatedAdminAdminTiersRoute
  AuthenticatedAdminAdminIndexRoute: typeof AuthenticatedAdminAdminIndexRoute
}

const AuthenticatedAdminAdminRouteChildren: AuthenticatedAdminAdminRouteChildren =
  {
    AuthenticatedAdminAdminCategoriesRoute:
      AuthenticatedAdminAdminCategoriesRoute,
    AuthenticatedAdminAdminCustomersRoute:
      AuthenticatedAdminAdminCustomersRoute,
    AuthenticatedAdminAdminLoyaltyRoute: AuthenticatedAdminAdminLoyaltyRoute,
    AuthenticatedAdminAdminOrdersRoute: AuthenticatedAdminAdminOrdersRoute,
    AuthenticatedAdminAdminProductsRoute: AuthenticatedAdminAdminProductsRoute,
    AuthenticatedAdminAdminStockRoute: AuthenticatedAdminAdminStockRoute,
    AuthenticatedAdminAdminTierDetailsRoute:
      AuthenticatedAdminAdminTierDetailsRoute,
    AuthenticatedAdminAdminTiersRoute: AuthenticatedAdminAdminTiersRoute,
    AuthenticatedAdminAdminIndexRoute: AuthenticatedAdminAdminIndexRoute,
  }

const AuthenticatedAdminAdminRouteWithChildren =
  AuthenticatedAdminAdminRoute._addFileChildren(
    AuthenticatedAdminAdminRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdminRoute: typeof AuthenticatedAdminAdminRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdminRoute: AuthenticatedAdminAdminRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedUserRouteChildren {
  AuthenticatedUserCartRoute: typeof AuthenticatedUserCartRoute
  AuthenticatedUserOrdersRoute: typeof AuthenticatedUserOrdersRoute
  AuthenticatedUserUserLoyaltyRoute: typeof AuthenticatedUserUserLoyaltyRoute
  AuthenticatedUserVoiceAssistantRoute: typeof AuthenticatedUserVoiceAssistantRoute
  AuthenticatedUserProductsProductIdRoute: typeof AuthenticatedUserProductsProductIdRoute
}

const AuthenticatedUserRouteChildren: AuthenticatedUserRouteChildren = {
  AuthenticatedUserCartRoute: AuthenticatedUserCartRoute,
  AuthenticatedUserOrdersRoute: AuthenticatedUserOrdersRoute,
  AuthenticatedUserUserLoyaltyRoute: AuthenticatedUserUserLoyaltyRoute,
  AuthenticatedUserVoiceAssistantRoute: AuthenticatedUserVoiceAssistantRoute,
  AuthenticatedUserProductsProductIdRoute:
    AuthenticatedUserProductsProductIdRoute,
}

const AuthenticatedUserRouteWithChildren =
  AuthenticatedUserRoute._addFileChildren(AuthenticatedUserRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedUserRoute: typeof AuthenticatedUserRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedUserRoute: AuthenticatedUserRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicAuthRoute: PublicAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
