import { resolve } from 'path';
import { loadEnvFile } from 'node:process';
import { existsSync } from 'node:fs';
import { PrismaPg } from '@prisma/adapter-pg';

// Load .env from project root
const envPath = resolve(__dirname, '../../../.env');
if (existsSync(envPath)) {
  loadEnvFile(envPath);
}

import { PrismaClient, PromotionStatus } from '../src/generated/prisma';

const databaseUrl = process.env['DATABASE_URL'];
if (!databaseUrl) {
  throw new Error(
    'DATABASE_URL is not set. Export it in your shell or create a workspace .env file before running prisma:bi-dashboard:seed.'
  );
}

const adapter = new PrismaPg({ connectionString: databaseUrl });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log('🌱 Starting BI Dashboard database seed...');
  console.log('ℹ️  Note: This seed creates minimal data for analytics visualization');
  console.log('ℹ️  Forecasts are generated by the ML service (bi-dashboard-ml-service)');
  console.log('ℹ️  User accounts are managed in the core schema\n');

  // Create Sample Products (aligned with core products structure)
  // In production, products should be imported/synced from core.products table
  // These seed products are for development/testing only
  //
  // Stock levels & reorder points for ML model testing:
  // - Average demand: ~136 units/day
  // - Reorder level: ~1.5 days supply
  // - Healthy stock: 3–5 days supply (400–700 units)
  const productData = [
    { sku: '916002', name: 'Ambarella', nameSi: 'ඇඹරැල්ලා', description: 'Tangy and fiber-rich local fruit used for chutneys and curries.', brand: 'unbranded', frequency: 'medium', price: 560, cost: 420, stock: 250, reorder: 80, max: 400 },
    { sku: '914000', name: 'Ash Plantains', nameSi: 'අළු කෙසෙල්', description: 'Starchy green cooking bananas ideal for deep frying or curries.', brand: 'unbranded', frequency: 'medium', price: 160, cost: 100, stock: 360, reorder: 100, max: 500 },
    { sku: '915001', name: 'Baby Potatoes', nameSi: 'බේබි අල', description: 'Small, tender potatoes with a thin skin, perfect for roasting whole.', brand: 'unbranded', frequency: 'medium', price: 700, cost: 450, stock: 60, reorder: 70, max: 450 },
    { sku: '912113', name: 'Basil Leaves 50g', nameSi: 'බැසිල් කොළ ග්‍රෑම් 50', description: 'Fragrant culinary herbs commonly used in Italian and Mediterranean dishes.', brand: 'unbranded', frequency: 'medium', price: 100, cost: 60, stock: 300, reorder: 120, max: 600 },
    { sku: '914004', name: 'Batana', nameSi: 'බටනා', description: 'A variety of local pumpkin known for its sweet and creamy texture.', brand: 'unbranded', frequency: 'medium', price: 380, cost: 280, stock: 50, reorder: 60, max: 350 },
    { sku: '915002', name: 'Beetroot', nameSi: 'බීට්රූට්', description: 'Vibrant red root vegetable rich in antioxidants and iron.', brand: 'unbranded', frequency: 'medium', price: 280, cost: 180, stock: 405, reorder: 100, max: 550 },
    { sku: '913005', name: 'Bell Pepper Green', nameSi: 'මාළු මිරිස් (කොළ)', description: 'Crisp green peppers with a mild, slightly bitter flavor.', brand: 'unbranded', frequency: 'medium', price: 620, cost: 450, stock: 200, reorder: 50, max: 300 },
    { sku: '913006', name: 'Bell Pepper Red', nameSi: 'මාළු මිරිස් (රතු)', description: 'Sweet and crunchy ripe peppers, excellent for salads and stir-fries.', brand: 'unbranded', frequency: 'medium', price: 760, cost: 550, stock: 205, reorder: 70, max: 350 },
    { sku: '941067', name: 'Thalapath Small', nameSi: 'තලපත් (කුඩා)', description: 'Fresh small-sized Sailfish.', brand: 'unbranded', frequency: 'medium', price: 2290, cost: 1750, stock: 30, reorder: 40, max: 200 },
    { sku: '913007', name: 'Bell Pepper Yellow', nameSi: 'මාළු මිරිස් (කහ)', description: 'Sweet, sunny-colored peppers that add brightness to any dish.', brand: 'unbranded', frequency: 'medium', price: 900, cost: 650, stock: 310, reorder: 55, max: 320 },
  ];

  const products = await Promise.all(
    productData.map((p) => {
      return prisma.product.upsert({
        where: { sku: p.sku },
        update: {
          name: p.name,
          nameSi: p.nameSi,
          description: p.description,
          price: p.price,
          brand: p.brand,
          purchaseFrequency: p.frequency,
          cost: p.cost,
          currentStock: p.stock,
          reorderLevel: p.reorder,
          maxStock: p.max,
          status: p.stock > p.reorder ? 'IN_STOCK' : p.stock > 0 ? 'LOW_STOCK' : 'OUT_OF_STOCK',
          supplier: 'Local Suppliers Ltd',
          competitorPricing: p.price * 1.05,
          lastRestocked: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
        },
        create: {
          sku: p.sku,
          name: p.name,
          nameSi: p.nameSi,
          description: p.description,
          price: p.price,
          brand: p.brand,
          purchaseFrequency: p.frequency,
          cost: p.cost,
          currentStock: p.stock,
          reorderLevel: p.reorder,
          maxStock: p.max,
          status: p.stock > p.reorder ? 'IN_STOCK' : p.stock > 0 ? 'LOW_STOCK' : 'OUT_OF_STOCK',
          supplier: 'Local Suppliers Ltd',
          competitorPricing: p.price * 1.05,
          lastRestocked: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000),
          isActive: true,
          createdBy: 'seed-script',
        },
      });
    })
  );
  console.log(`✅ ${products.length} products created/updated (using SKU as identifier)`);

  // Create Sales transactions (30 days history)
  // Sales data is needed for analytics dashboards and frontend charts showing:
  // - Daily revenue trends
  // - Sales by product category
  // - Payment method breakdowns
  // - Top products by volume/revenue
  console.log('📊 Creating 30-day sales history...');
  const existingSalesCount = await prisma.sale.count();
  if (existingSalesCount > 0) {
    console.log(`⏭️  Skipping sales - ${existingSalesCount} transactions already exist`);
  } else {
    // Build sale rows and item rows separately for batch inserts (2 queries instead of N)
    const saleRows: any[] = [];
    const itemRows: any[] = [];

    for (let day = 0; day < 30; day++) {
      const txCount = Math.floor(Math.random() * 5) + 3;
      for (let tx = 0; tx < txCount; tx++) {
        const timestamp = new Date(Date.now() - day * 24 * 60 * 60 * 1000 + Math.random() * 24 * 60 * 60 * 1000);
        const itemCount = Math.floor(Math.random() * 3) + 1;
        const saleId = `SAL-${day}-${tx}-${Date.now()}`;
        let totalAmount = 0;

        for (let i = 0; i < itemCount; i++) {
          const product = products[Math.floor(Math.random() * products.length)];
          const quantity = Math.floor(Math.random() * 3) + 1;
          const revenue = product.price * quantity;
          const cost = (product.cost ?? 0) * quantity;
          totalAmount += revenue;
          itemRows.push({
            id: `${saleId}-item-${i}`,
            saleId,
            productId: product.id,
            quantity,
            unitPrice: product.price,
            revenue,
            cost,
            profit: revenue - cost,
          });
        }

        const discount = Math.random() < 0.3 ? totalAmount * 0.1 : 0;
        const txnNumber = (29 - day) * 100 + tx;
        saleRows.push({
          id: saleId,
          transactionId: `TXN-${new Date(timestamp).toISOString().split('T')[0]}-${String(txnNumber).padStart(6, '0')}`,
          customerId: null, // BI tracks sales, not customers - customer data is in core schema
          totalAmount,
          discount,
          finalAmount: totalAmount - discount,
          paymentMethod: (['CASH', 'CARD', 'MOBILE'] as const)[Math.floor(Math.random() * 3)],
          timestamp,
        });
      }
    }

    await prisma.sale.createMany({ data: saleRows });
    await prisma.saleItem.createMany({ data: itemRows });
    console.log(`✅ ${saleRows.length} sales transactions created (${itemRows.length} items)`);
  }

  // === FORECASTS: ML Service Responsibility ===
  // The ML service (bi-dashboard-ml-service) automatically generates:
  // 1. Forecast records - predicted daily sales with confidence intervals
  // 2. ForecastDriver records - factors explaining the forecast (seasonality, stock coverage, promotions)
  //
  // We DO NOT seed forecasts here because:
  // - Mock data is unrealistic and not useful for analytics
  // - The ML pipeline continuously updates forecasts with actual model output
  // - Stale mock forecasts would be misleading in the dashboard
  //
  // If you need immediate data for frontend development, the ML service should be running
  // or you can manually insert test forecasts matching the ML model's output format.
  console.log('✅ Forecast seeding skipped (handled by ML service at runtime)');

  // Seed sample alerts based on reorder levels
  // Alerts are auto-generated when stock falls below reorder threshold
  // These examples show what the dashboard will display
  console.log('🔔 Creating restock alerts based on inventory levels...');

  const existingAlertsCount = await prisma.alert.count();
  if (existingAlertsCount === 0) {
    const lowStockProducts = products
      .filter((product) => product.currentStock <= product.reorderLevel)
      .slice(0, 3);

    if (lowStockProducts.length > 0) {
      const seededAlerts = lowStockProducts.map((product, index) => ({
        type: 'RESTOCK' as const,
        urgency: index === 0 ? ('HIGH' as const) : ('MEDIUM' as const),
        productId: product.id,
        currentStock: product.currentStock,
        recommendedQuantity: Math.max(product.reorderLevel - product.currentStock + 40, 20),
        reason: `${product.name} is below the reorder threshold and should be replenished soon.`,
        reasonSi: `${product.nameSi} නැවත ඇණවුම් සීමාවට අඩු වී ඇත. ඉක්මනින් නැවත පුරවන්න.`,
        confidence: 0.91 - index * 0.05,
        estimatedStockoutDate: new Date(Date.now() + (7 + index * 3) * 24 * 60 * 60 * 1000),
        status: 'PENDING' as const,
      }));

      await prisma.alert.createMany({ data: seededAlerts });
      console.log(`✅ ${seededAlerts.length} sample alerts created`);
    } else {
      console.log('⏭️  No products below reorder level - skipping alerts');
    }
  }

  // Seed minimal promotion data for UI structure
  // In production, promotions are created through the admin UI
  console.log('🎯 Creating sample promotion...');
  const promotionData = {
    name: 'Weekend Special',
    nameSi: 'සති අන්ත විශේෂය',
    discount: 15,
    startDate: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000),
    status: PromotionStatus.ACTIVE,
    targetedRevenue: 50000,
    actualRevenue: 32000,
    lift: 22.5,
  };

  const promotion = await prisma.promotion.upsert({
    where: { id: 'PRM001' },
    update: promotionData,
    create: { id: 'PRM001', ...promotionData },
  });

  // Delete existing promotion products and recreate
  await prisma.promotionProduct.deleteMany({
    where: { promotionId: promotion.id },
  });

  // Link first 3 products to promotion (dynamic IDs)
  await prisma.promotionProduct.createMany({
    data: products.slice(0, 3).map((product) => ({
      promotionId: promotion.id,
      productId: product.id,
    })),
  });
  console.log('✅ Promotion created/updated');

  console.log('\n🎉 Database seeding completed successfully!');
  console.log('\n📊 BI Dashboard Data Overview:');
  console.log(`  ✅ Products: ${products.length} items for inventory analytics (synced with core products via SKU)`);
  console.log('  ✅ Sales History: 30 days of transactions for charts & trends');
  console.log('  ✅ Alerts: Sample restock alerts based on reorder levels');
  console.log('  ✅ Promotions: 1 sample promotion structure');
  console.log('  ⏭️  Forecasts: Generated by ML service at runtime (NOT seeded)');
  console.log('  ⏭️  Forecast Drivers: Generated by ML service (NOT seeded)');
  console.log('\n🔄 Data Sync Strategy:');
  console.log('  • Use SKU as the unique identifier for product sync');
  console.log('  • Product UUIDs are auto-generated (matches core structure)');
  console.log('  • upsert by SKU to merge core products with BI-specific data');
  console.log('  • Example: prisma.product.upsert({ where: { sku: "916002" }, ... })');
  console.log('\n💡 To Import Core Products:');
  console.log('  1. Set up bi_dashboard schema in your core database');
  console.log('\n💡 Next Steps:');
  console.log('  1. Run the ML service: pnpm nx run bi-dashboard-ml-service:serve');
  console.log('  2. Start the BI gateway: pnpm nx run bi-dashboard-services-gateway:serve');
  console.log('  3. Access dashboard at: /bi/analytics/dashboard');
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });