/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicTwoFactorIndexRouteImport } from './routes/_public/two-factor/index'
import { Route as PublicSignupIndexRouteImport } from './routes/_public/signup/index'
import { Route as PublicSigninIndexRouteImport } from './routes/_public/signin/index'
import { Route as PublicForgotPasswordIndexRouteImport } from './routes/_public/forgot-password/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicTwoFactorIndexRoute = PublicTwoFactorIndexRouteImport.update({
  id: '/two-factor/',
  path: '/two-factor/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSignupIndexRoute = PublicSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninIndexRoute = PublicSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordIndexRoute =
  PublicForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => PublicRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/forgot-password/': typeof PublicForgotPasswordIndexRoute
  '/signin/': typeof PublicSigninIndexRoute
  '/signup/': typeof PublicSignupIndexRoute
  '/two-factor/': typeof PublicTwoFactorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/forgot-password': typeof PublicForgotPasswordIndexRoute
  '/signin': typeof PublicSigninIndexRoute
  '/signup': typeof PublicSignupIndexRoute
  '/two-factor': typeof PublicTwoFactorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_public/forgot-password/': typeof PublicForgotPasswordIndexRoute
  '/_public/signin/': typeof PublicSigninIndexRoute
  '/_public/signup/': typeof PublicSignupIndexRoute
  '/_public/two-factor/': typeof PublicTwoFactorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/forgot-password/'
    | '/signin/'
    | '/signup/'
    | '/two-factor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/signin'
    | '/signup'
    | '/two-factor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/dashboard/'
    | '/_public/forgot-password/'
    | '/_public/signin/'
    | '/_public/signup/'
    | '/_public/two-factor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/two-factor/': {
      id: '/_public/two-factor/'
      path: '/two-factor'
      fullPath: '/two-factor/'
      preLoaderRoute: typeof PublicTwoFactorIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signup/': {
      id: '/_public/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof PublicSignupIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin/': {
      id: '/_public/signin/'
      path: '/signin'
      fullPath: '/signin/'
      preLoaderRoute: typeof PublicSigninIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password/': {
      id: '/_public/forgot-password/'
      path: '/forgot-password'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof PublicForgotPasswordIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicForgotPasswordIndexRoute: typeof PublicForgotPasswordIndexRoute
  PublicSigninIndexRoute: typeof PublicSigninIndexRoute
  PublicSignupIndexRoute: typeof PublicSignupIndexRoute
  PublicTwoFactorIndexRoute: typeof PublicTwoFactorIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicForgotPasswordIndexRoute: PublicForgotPasswordIndexRoute,
  PublicSigninIndexRoute: PublicSigninIndexRoute,
  PublicSignupIndexRoute: PublicSignupIndexRoute,
  PublicTwoFactorIndexRoute: PublicTwoFactorIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
